### ISSUE TITLE
Failing OctoDash

### ISSUE THREAD

**Issue by JNSmith1717** [MatthewCroughan/octobalena#13]
when building release its failing on octodash

**Comment by SamEureka** [comment]
+1
```
[Error]           Some services failed to build:
[Error]             Service: octodash
[Error]               Error: The command '/bin/sh -c curl -sL https://github.com/UnchartedBull/
OctoDash/releases/download/v""$VERSION""/octodash_""$VERSION""_$(uname -m).deb 
-o octodash.deb &&     dpkg -i --ignore-depends=libnotify4,xdg-utils,libappindicator3-1,
libsecret-1-0 octodash.deb &&     rm octodash.deb' returned a non-zero code: 1
```
(line breaks added for readability)

**Comment by MatthewCroughan** [comment]
I do not have time to debug and solve this issue outright at the moment, but if anyone else could look into this and fix it, that would be great.

I'm not sure how this broke, but maybe the `dpkg -i` is failing now because the release was silently changed for that version by UnchartedBull? What is the $VERSION you're using in the file? It's possible that it's just that, so try bumping it up to the current Octodash version, which is `2.0.0` and rebuilding.

**Comment by SamEureka** [comment]
I'll fork and see what I can do. Thanks for pointing me in a direction.
